runner:
  cljstyle:
    cmd: cljstyle check
    format: diff
    name: cljstyle
  clj-kondo:
    cmd: clj-kondo --lint src --config .clj-kondo/ci-config.edn
    format: errorformat
    name: clj-kondo
