runner:
  cljstyle:
    cmd: cljstyle check --report
    format: diff
    name: ClojureFormat
  clj-kondo:
    cmd: clj-kondo --lint src --config .clj-kondo/ci-config.edn
    format: rdjson
    name: ClojureLinter
